CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE expense_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  currency VARCHAR(3) NOT NULL,
  owner_id BIGINT REFERENCES app_user(id) NOT NULL
);

CREATE TABLE membership (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  group_id BIGINT REFERENCES expense_group(id) NOT NULL,
  user_id BIGINT REFERENCES app_user(id) NOT NULL,
  role VARCHAR(16) NOT NULL,
  UNIQUE(group_id,user_id),
  CHECK(role IN ('ADMIN','MEMBER'))
);

CREATE TABLE category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE expense (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  group_id BIGINT REFERENCES expense_group(id) NOT NULL,
  paid_by_id BIGINT REFERENCES app_user(id) NOT NULL,
  created_by_id BIGINT REFERENCES app_user(id) NOT NULL,
  category_id BIGINT REFERENCES category(id),
  description VARCHAR(250) NOT NULL,
  original_amount NUMERIC(15,2) NOT NULL,
  original_currency VARCHAR(3) NOT NULL,
  settlement_amount NUMERIC(15,2) NOT NULL,
  exchange_rate NUMERIC(28,12),
  rate_date DATE,
  expense_date DATE NOT NULL,
  split_method VARCHAR(20) NOT NULL,
  version BIGINT,
  CHECK(original_amount > 0),
  CHECK(settlement_amount > 0),
  CHECK(exchange_rate IS NULL OR exchange_rate > 0)
);

CREATE TABLE expense_share (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expense_id BIGINT REFERENCES expense(id) NOT NULL,
  user_id BIGINT REFERENCES app_user(id) NOT NULL,
  share_amount NUMERIC(15,2) NOT NULL,
  UNIQUE(expense_id,user_id),
  CHECK(share_amount >= 0)
);

CREATE INDEX idx_expense_group ON expense(group_id, expense_date);
CREATE INDEX idx_membership_user ON membership(user_id);
CREATE INDEX idx_share_expense ON expense_share(expense_id);
INSERT INTO category(name,created_at,updated_at) VALUES ('Lebensmittel',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO category(name,created_at,updated_at) VALUES ('Unterkunft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO category(name,created_at,updated_at) VALUES ('Fahrtkosten',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO category(name,created_at,updated_at) VALUES ('Freizeit',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO category(name,created_at,updated_at) VALUES ('Haushalt',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO category(name,created_at,updated_at) VALUES ('Sonstiges',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
