CREATE TABLE repayment (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMP WITH TIME ZONE NOT NULL,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
group_id BIGINT NOT NULL REFERENCES expense_group(id),
sender_id BIGINT NOT NULL REFERENCES app_user(id),
recipient_id BIGINT NOT NULL REFERENCES app_user(id),
recorded_by_id BIGINT NOT NULL REFERENCES app_user(id),
amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
payment_date DATE NOT NULL,
CHECK (sender_id <> recipient_id)
);
CREATE INDEX idx_repayment_group ON repayment(group_id, payment_date);
