CREATE TABLE expense_change (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 group_id BIGINT NOT NULL REFERENCES expense_group(id),
 expense_id BIGINT NOT NULL,
 actor_id BIGINT NOT NULL,
 actor_name VARCHAR(255) NOT NULL,
 details TEXT NOT NULL
);
CREATE INDEX ix_expense_change_group ON expense_change(group_id, id);
